name: Fetch Trello Daily Tasks

on:
  schedule:
    - cron: '0 11 * * *'  # Daily at 11:00 UTC
  workflow_dispatch:

jobs:
  fetch-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run Trello fetch script
        run: node scripts/fetchTrello.js
        env:
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}

      - name: Commit and push JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/dailyTasks.json
          git commit -m "Update daily tasks"
          git push
